name: Build NextClient

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install ninja-build

    - name: Build project
      run: |
        mkdir -p cmake-build-release
        cd cmake-build-release
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target BUILD_ALL
