name: Build NextClient

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg integrate install
        ./vcpkg/vcpkg install

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build -y

    - name: Build project
      run: |
        mkdir -p cmake-build-release
        cd cmake-build-release
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build . --target BUILD_ALL
